/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entities.*;

import javax.swing.*;
import java.awt.*;

/**
 * A GUI class that assist the administrator and facilitate creation a new class in the database.
 * Creation of a new class is done through creation of new course and assign the class to it.
 * Creation of courses is done through entering some data (course name and course code).
 * Creation of classes is done through entering some data (course code).
 * All data that entered is checked by validating functions.
 *
 * @author AbdelAziz Mostafa
 */
public class AddNewClass extends javax.swing.JFrame {
    Admin admin;
    private final java.awt.Font myFont1 = new java.awt.Font("Tahoma", Font.BOLD, 13);


    /**
     * Creates new form AddNewClass
     */
    public AddNewClass(Admin admin) {
        this.admin = admin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultState="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JButton logoutButton = new javax.swing.JButton();
        javax.swing.JLabel title = new javax.swing.JLabel();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JButton backButton = new javax.swing.JButton();
        courseCodeTextField2 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JButton addCourseButton = new javax.swing.JButton();
        javax.swing.JButton addNewClassButton = new javax.swing.JButton();
        courseCodeTextField = new javax.swing.JTextField();
        CourseNameTextField = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(134, 171, 161));

        logoutButton.setFont(myFont1); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(evt -> LogoutButtonActionPerformed());

        title.setFont(new java.awt.Font("Tahoma", Font.BOLD, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        title.setText("Add New Class");
        title.setFocusTraversalPolicyProvider(true);

        backButton.setFont(myFont1); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(evt -> BackButtonActionPerformed());

        jLabel1.setText("CourseCode");

        addCourseButton.setText("Add Course");
        addCourseButton.addActionListener(evt -> addCourseButtonActionPerformed());

        addNewClassButton.setText("Add new Class");
        addNewClassButton.addActionListener(evt -> addNewClassButtonActionPerformed());

        jLabel3.setText("CourseCode");

        jLabel4.setText("Course Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(title)
                                .addGap(61, 61, 61)
                                .addComponent(logoutButton)
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(CourseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(courseCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(136, 136, 136)
                                                .addComponent(courseCodeTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(170, 170, 170)
                                                .addComponent(addCourseButton))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(161, 161, 161)
                                                .addComponent(addNewClassButton)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(title)
                                        .addComponent(logoutButton)
                                        .addComponent(backButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(courseCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CourseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(addCourseButton)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(courseCodeTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addNewClassButton)
                                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed() {//GEN-FIRST:event_LogoutButtonActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void BackButtonActionPerformed() {//GEN-FIRST:event_BackButtonActionPerformed
        new AdminDashboard(admin.getUsername()).setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void addCourseButtonActionPerformed() {//GEN-FIRST:event_addCourseButtonActionPerformed
        if (isAllWhiteSpaces(CourseNameTextField.getText()) || isAllWhiteSpaces(courseCodeTextField.getText())) {
            //This message appear if the user try to press add button without filling all data.
            JOptionPane.showMessageDialog(null, "You should fill out all text fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (Course.isCourseCodeExisted(courseCodeTextField.getText())) {
            // This message appear if the user try to enter an existing course name.
            JOptionPane.showMessageDialog(null, "This is an invalid course code", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Adding new course in the database.
        new Course(courseCodeTextField.getText(), CourseNameTextField.getText()).add();

        // This message appear if the course is successfully added into database.
        JOptionPane.showMessageDialog(null, "Add Course successfully", "", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_addCourseButtonActionPerformed

    /**
     * Checking if the data is empty or not.
     * if the whole string is whitespaces it returns true
     * else it returns false
     *
     * @param data string variable that carry the data (password, email, etc..) to check if it is empty or not.
     * @return boolean.
     */
    private boolean isAllWhiteSpaces(String data) {
        int whiteSpaceFreq = 0;
        for (char c : data.toCharArray()) {
            if (c == ' ')
                whiteSpaceFreq++;
        }
        return whiteSpaceFreq == data.length();
    }

    private void addNewClassButtonActionPerformed() {//GEN-FIRST:event_addNewClassButtonActionPerformed
        if (isAllWhiteSpaces(courseCodeTextField2.getText())) {
            //This message appear if the user try to press add button without filling all data.
            JOptionPane.showMessageDialog(null, "You should fill out the text field", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Course.isCourseCodeExisted(courseCodeTextField2.getText())) {
            // This message appear if the user try to enter an invalid course code.
            JOptionPane.showMessageDialog(null, "This is an invalid course code", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Create a sequence for classes.
        int id = Entities.SqlEntity.generateID("CLASSIDSEQ");

        //Adding new class into database.
        new Entities.Class(id, new Course(courseCodeTextField2.getText())).add();

        // This message appear if the class successfully added in the system.
        JOptionPane.showMessageDialog(null, "Add class with ID: " + id + " successfully", "", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_addNewClassButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddNewClass(new Admin("admin")).setVisible(true));
    }

    private javax.swing.JTextField CourseNameTextField;
    private javax.swing.JTextField courseCodeTextField;
    private javax.swing.JTextField courseCodeTextField2;
    // End of variables declaration//GEN-END:variables
}
