/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.*;
import javax.swing.JOptionPane;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;


/**
 *
 * @author yn653
 */
public class CreateQuestion extends javax.swing.JFrame {

    /**
     * Creates new form CreateQuestion
     */
    public CreateQuestion() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        createQuestPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionTextArea = new javax.swing.JTextArea();
        enterQuestLabel = new javax.swing.JLabel();
        option1Label = new javax.swing.JLabel();
        option2Label = new javax.swing.JLabel();
        option2TextField = new javax.swing.JTextField();
        option1TextField = new javax.swing.JTextField();
        option4TextField = new javax.swing.JTextField();
        option4Label = new javax.swing.JLabel();
        option3Label = new javax.swing.JLabel();
        option3TextField = new javax.swing.JTextField();
        option1Rad = new javax.swing.JRadioButton();
        option2Rad = new javax.swing.JRadioButton();
        option3Rad = new javax.swing.JRadioButton();
        option4Rad = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createQuestPanel.setBackground(new java.awt.Color(134, 171, 161));

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        questionTextArea.setColumns(20);
        questionTextArea.setRows(5);
        jScrollPane1.setViewportView(questionTextArea);

        enterQuestLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterQuestLabel.setText("Enter the question body here : ");

        option1Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        option1Label.setText("Enter option 1");

        option2Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        option2Label.setText("Enter option 2");

        option1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1TextFieldActionPerformed(evt);
            }
        });

        option4Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        option4Label.setText("Enter option 4");

        option3Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        option3Label.setText("Enter option 3");

        option1Rad.setBackground(new java.awt.Color(134, 171, 161));
        buttonGroup1.add(option1Rad);
        option1Rad.setText("A");

        option2Rad.setBackground(new java.awt.Color(134, 171, 161));
        buttonGroup1.add(option2Rad);
        option2Rad.setText("B");
        option2Rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2RadActionPerformed(evt);
            }
        });

        option3Rad.setBackground(new java.awt.Color(134, 171, 161));
        buttonGroup1.add(option3Rad);
        option3Rad.setText("C");

        option4Rad.setBackground(new java.awt.Color(134, 171, 161));
        buttonGroup1.add(option4Rad);
        option4Rad.setText("D");

        javax.swing.GroupLayout createQuestPanelLayout = new javax.swing.GroupLayout(createQuestPanel);
        createQuestPanel.setLayout(createQuestPanelLayout);
        createQuestPanelLayout.setHorizontalGroup(
            createQuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createQuestPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createQuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createQuestPanelLayout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(finishButton))
                    .addGroup(createQuestPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoutButton)))
                .addGap(20, 20, 20))
            .addGroup(createQuestPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(createQuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterQuestLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(createQuestPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(createQuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(createQuestPanelLayout.createSequentialGroup()
                                .addGroup(createQuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(option4Label)
                                    .addComponent(option3Label))
                                .addGap(26, 26, 26)
                                .addGroup(createQuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(option3TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                    .addComponent(option4TextField)))
                            .addGroup(createQuestPanelLayout.createSequentialGroup()
                                .addGroup(createQuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(option2Label)
                                    .addComponent(option1Label))
                                .addGap(26, 26, 26)
                                .addGroup(createQuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(option2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                    .addComponent(option1TextField))))
                        .addGap(39, 39, 39)
                        .addGroup(createQuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(option1Rad)
                            .addComponent(option2Rad)
                            .addComponent(option3Rad)
                            .addComponent(option4Rad))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        createQuestPanelLayout.setVerticalGroup(
            createQuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createQuestPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(logoutButton)
                .addGap(38, 38, 38)
                .addComponent(enterQuestLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(createQuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option1Label)
                    .addComponent(option1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option1Rad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createQuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option2Label)
                    .addComponent(option2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option2Rad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createQuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option3Label)
                    .addComponent(option3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option3Rad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createQuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option4Label)
                    .addComponent(option4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option4Rad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addGroup(createQuestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(finishButton)
                    .addComponent(backButton)
                    .addComponent(cancelButton))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createQuestPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createQuestPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        boolean successFill = questionValidality();//this boolean will be used to store data into database 
            
        
    }//GEN-LAST:event_nextButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        new Login();
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        int cancelChoice = JOptionPane.showConfirmDialog(new JFrame(), "Are you sure?");
        if(cancelChoice==JOptionPane.YES_OPTION){  
            new CreateExam();
            dispose();
        }  
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void option1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option1TextFieldActionPerformed

    private void option2RadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2RadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option2RadActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        // TODO add your handling code here:
        int finishChoice = JOptionPane.showConfirmDialog(new JFrame(), "Are you sure?");
        if(finishChoice == JOptionPane.YES_OPTION){  
            if(questionValidality()){
                new CreateExam();
                dispose();
            }
        }
    }//GEN-LAST:event_finishButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        // When database is ready
    }//GEN-LAST:event_backButtonActionPerformed
    
    /** Yusuf Nasser 31st Dec 2020 12:14
     * This method validates that the user input doesn't consist completely of white spaces
     * @param data The data inputted by the user
     * @return true if data is consisted of only white spaces; false otherwise.
     */
    
    private boolean isAllWhiteSpaces(String data){
        int whiteSpaceFreq = 0;
        for(char c : data.toCharArray())
        {
            if (c == ' ')
                whiteSpaceFreq++;
        }
        return whiteSpaceFreq == data.length();
    }
    
    private boolean questionValidality(){
        boolean errorFound = false;
        String getQuestion = questionTextArea.getText();
        String getOption1 = option1TextField.getText();
        String getOption2 = option2TextField.getText();
        String getOption3 = option3TextField.getText();
        String getOption4 = option4TextField.getText();
        String getCorrectOption = "";
       
        for (Enumeration<AbstractButton> buttons = buttonGroup1.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                getCorrectOption = button.getText();
            
            }
        }
        
        if (getOption1.length() == 0 || getOption2.length() == 0
                || getOption3.length() == 0 || getOption4.length() == 0){
            JOptionPane.showMessageDialog(null, "You should fill out all text fields", "Error", JOptionPane.ERROR_MESSAGE);
            errorFound = true;
            return false;            
        }
        
        /* Yusuf Nasser 31st Dec 2020 12:10 
        * Bug Hunted by Ayman Hassan
        * Validating that the user input doesn't consist completely of white space
        */
        
        if (isAllWhiteSpaces(getQuestion) || isAllWhiteSpaces(getOption1) || isAllWhiteSpaces(getOption2)
                || isAllWhiteSpaces(getOption3) || isAllWhiteSpaces(getOption4))
        {
            JOptionPane.showMessageDialog(null, "White Spaces Do NOT count as an answer nor as a question", "Error", JOptionPane.ERROR_MESSAGE);
            errorFound = true;
            return false; 
        }
        
        if(getCorrectOption.length() == 0){
            JOptionPane.showMessageDialog(null, "You should choose the correct answer", "Error", JOptionPane.ERROR_MESSAGE);
            errorFound = true;
            return false;

        }
        if (getQuestion.length() == 0){
            JOptionPane.showMessageDialog(null, "You should enter the question body", "Error", JOptionPane.ERROR_MESSAGE);
            errorFound = true;
            return false;
        }
        if(errorFound == false){
        JOptionPane.showMessageDialog(null, "You have added a question successfuly", "success", JOptionPane.INFORMATION_MESSAGE);
        questionTextArea.setText("");
        option1TextField.setText("");
        option2TextField.setText("");
        option3TextField.setText("");
        option4TextField.setText("");
        buttonGroup1.clearSelection();
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel createQuestPanel;
    private javax.swing.JLabel enterQuestLabel;
    private javax.swing.JButton finishButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel option1Label;
    private javax.swing.JRadioButton option1Rad;
    private javax.swing.JTextField option1TextField;
    private javax.swing.JLabel option2Label;
    private javax.swing.JRadioButton option2Rad;
    private javax.swing.JTextField option2TextField;
    private javax.swing.JLabel option3Label;
    private javax.swing.JRadioButton option3Rad;
    private javax.swing.JTextField option3TextField;
    private javax.swing.JLabel option4Label;
    private javax.swing.JRadioButton option4Rad;
    private javax.swing.JTextField option4TextField;
    private javax.swing.JTextArea questionTextArea;
    // End of variables declaration//GEN-END:variables
}
