/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author yn653
 */
public class ExamPaper extends javax.swing.JFrame {

    /**
     * Creates new form ExamPaper
     */
    public ExamPaper() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        examInfrormationPanel = new javax.swing.JPanel();
        subjectNameLabel = new javax.swing.JLabel();
        subjectNamePlaceholderLabel = new javax.swing.JLabel();
        examDateLabel = new javax.swing.JLabel();
        examDatePlaceholderLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        instructorNamePlaceholderLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        endTimePlaceholderLabel = new javax.swing.JLabel();
        durationPlaceholderLabel = new javax.swing.JLabel();
        examQuestionPnael = new javax.swing.JPanel();
        question1PlaceholderLabel = new javax.swing.JLabel();
        ques1Rad1 = new javax.swing.JRadioButton();
        ques1Rad2 = new javax.swing.JRadioButton();
        ques1Rad3 = new javax.swing.JRadioButton();
        ques1Rad4 = new javax.swing.JRadioButton();
        question2PlaceholderLabel = new javax.swing.JLabel();
        ques2Rad1 = new javax.swing.JRadioButton();
        ques2Rad2 = new javax.swing.JRadioButton();
        ques2Rad3 = new javax.swing.JRadioButton();
        ques2Rad4 = new javax.swing.JRadioButton();
        question3PlaceholderLabel = new javax.swing.JLabel();
        ques3Rad4 = new javax.swing.JRadioButton();
        ques3Rad3 = new javax.swing.JRadioButton();
        ques3Rad2 = new javax.swing.JRadioButton();
        ques3Rad1 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        question6PlaceholderLabel = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        ques1Rad5 = new javax.swing.JRadioButton();
        ques1Rad6 = new javax.swing.JRadioButton();
        ques1Rad7 = new javax.swing.JRadioButton();
        ques1Rad8 = new javax.swing.JRadioButton();
        question4PlaceholderLabel = new javax.swing.JLabel();
        question5PlaceholderLabel = new javax.swing.JLabel();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        question9PlaceholderLabel = new javax.swing.JLabel();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        ques1Rad9 = new javax.swing.JRadioButton();
        ques1Rad10 = new javax.swing.JRadioButton();
        ques1Rad11 = new javax.swing.JRadioButton();
        ques1Rad12 = new javax.swing.JRadioButton();
        question7PlaceholderLabel = new javax.swing.JLabel();
        question8PlaceholderLabel = new javax.swing.JLabel();
        question10PlaceholderLabel = new javax.swing.JLabel();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(134, 171, 161));

        examInfrormationPanel.setPreferredSize(new java.awt.Dimension(760, 111));

        fcisLabel.setText("FCIS - Ain Shams University");

        subjectNameLabel.setText("Sublect : ");

        subjectNamePlaceholderLabel.setText("subjectplaceholder");

        examDateLabel.setText("Exam Date : ");

        examDatePlaceholderLabel.setText("examDatePlaceholder");

        jLabel1.setText("Instructor : ");

        instructorNamePlaceholderLabel.setText("instructorNamePlaceholder");

        jLabel2.setText("Start Time : ");

        jLabel3.setText("End Time : ");

        jLabel4.setText("Duration : ");

        jLabel5.setText("startTimePlaceholder");

        endTimePlaceholderLabel.setText("endTimePlaceholder");

        durationPlaceholderLabel.setText("durationPlaceholder");
        durationPlaceholderLabel.setToolTipText("");

        javax.swing.GroupLayout examInfrormationPanelLayout = new javax.swing.GroupLayout(examInfrormationPanel);
        examInfrormationPanel.setLayout(examInfrormationPanelLayout);
        examInfrormationPanelLayout.setHorizontalGroup(
            examInfrormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examInfrormationPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(examInfrormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fcisLabel)
                    .addGroup(examInfrormationPanelLayout.createSequentialGroup()
                        .addComponent(subjectNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subjectNamePlaceholderLabel))
                    .addGroup(examInfrormationPanelLayout.createSequentialGroup()
                        .addComponent(examDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(examDatePlaceholderLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(examInfrormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(examInfrormationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(durationPlaceholderLabel))
                    .addGroup(examInfrormationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endTimePlaceholderLabel))
                    .addGroup(examInfrormationPanelLayout.createSequentialGroup()
                        .addGroup(examInfrormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(examInfrormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(instructorNamePlaceholderLabel))))
                .addGap(40, 40, 40))
        );
        examInfrormationPanelLayout.setVerticalGroup(
            examInfrormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examInfrormationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(examInfrormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fcisLabel)
                    .addComponent(jLabel1)
                    .addComponent(instructorNamePlaceholderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(examInfrormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectNameLabel)
                    .addComponent(subjectNamePlaceholderLabel)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(examInfrormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(examDateLabel)
                    .addComponent(examDatePlaceholderLabel)
                    .addComponent(jLabel3)
                    .addComponent(endTimePlaceholderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(examInfrormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(durationPlaceholderLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        question1PlaceholderLabel.setText("Question 1 Placeholder");

        buttonGroup1.add(ques1Rad1);
        ques1Rad1.setText("jRadioButton1");

        buttonGroup1.add(ques1Rad2);
        ques1Rad2.setText("jRadioButton2");

        buttonGroup1.add(ques1Rad3);
        ques1Rad3.setText("jRadioButton3");

        buttonGroup1.add(ques1Rad4);
        ques1Rad4.setText("jRadioButton4");

        question2PlaceholderLabel.setText("Question 2 Placeholder");

        buttonGroup2.add(ques2Rad1);
        ques2Rad1.setText("jRadioButton1");

        buttonGroup2.add(ques2Rad2);
        ques2Rad2.setText("jRadioButton2");

        buttonGroup2.add(ques2Rad3);
        ques2Rad3.setText("jRadioButton3");

        buttonGroup2.add(ques2Rad4);
        ques2Rad4.setText("jRadioButton4");

        question3PlaceholderLabel.setText("Question 3 Placeholder");

        buttonGroup3.add(ques3Rad4);
        ques3Rad4.setText("jRadioButton4");

        buttonGroup3.add(ques3Rad3);
        ques3Rad3.setText("jRadioButton3");

        buttonGroup3.add(ques3Rad2);
        ques3Rad2.setText("jRadioButton2");

        buttonGroup3.add(ques3Rad1);
        ques3Rad1.setText("jRadioButton1");

        buttonGroup6.add(jRadioButton9);
        jRadioButton9.setText("jRadioButton4");

        buttonGroup6.add(jRadioButton10);
        jRadioButton10.setText("jRadioButton3");

        buttonGroup6.add(jRadioButton11);
        jRadioButton11.setText("jRadioButton2");

        buttonGroup6.add(jRadioButton12);
        jRadioButton12.setText("jRadioButton1");

        question6PlaceholderLabel.setText("Question 6 Placeholder");

        buttonGroup5.add(jRadioButton13);
        jRadioButton13.setText("jRadioButton1");

        buttonGroup5.add(jRadioButton14);
        jRadioButton14.setText("jRadioButton2");

        buttonGroup5.add(jRadioButton15);
        jRadioButton15.setText("jRadioButton3");

        buttonGroup5.add(jRadioButton16);
        jRadioButton16.setText("jRadioButton4");

        buttonGroup4.add(ques1Rad5);
        ques1Rad5.setText("jRadioButton4");

        buttonGroup4.add(ques1Rad6);
        ques1Rad6.setText("jRadioButton3");

        buttonGroup4.add(ques1Rad7);
        ques1Rad7.setText("jRadioButton2");

        buttonGroup4.add(ques1Rad8);
        ques1Rad8.setText("jRadioButton1");

        question4PlaceholderLabel.setText("Question 4 Placeholder");

        question5PlaceholderLabel.setText("Question 5 Placeholder");

        buttonGroup9.add(jRadioButton17);
        jRadioButton17.setText("jRadioButton4");

        buttonGroup9.add(jRadioButton18);
        jRadioButton18.setText("jRadioButton3");

        buttonGroup9.add(jRadioButton19);
        jRadioButton19.setText("jRadioButton2");

        buttonGroup9.add(jRadioButton20);
        jRadioButton20.setText("jRadioButton1");

        question9PlaceholderLabel.setText("Question 9 Placeholder");

        buttonGroup8.add(jRadioButton21);
        jRadioButton21.setText("jRadioButton1");

        buttonGroup8.add(jRadioButton22);
        jRadioButton22.setText("jRadioButton2");

        buttonGroup8.add(jRadioButton23);
        jRadioButton23.setText("jRadioButton3");

        buttonGroup8.add(jRadioButton24);
        jRadioButton24.setText("jRadioButton4");

        buttonGroup7.add(ques1Rad9);
        ques1Rad9.setText("jRadioButton4");

        buttonGroup7.add(ques1Rad10);
        ques1Rad10.setText("jRadioButton3");

        buttonGroup7.add(ques1Rad11);
        ques1Rad11.setText("jRadioButton2");

        buttonGroup7.add(ques1Rad12);
        ques1Rad12.setText("jRadioButton1");

        question7PlaceholderLabel.setText("Question 7 Placeholder");

        question8PlaceholderLabel.setText("Question 8 Placeholder");

        question10PlaceholderLabel.setText("Question 10 Placeholder");

        buttonGroup10.add(jRadioButton25);
        jRadioButton25.setText("jRadioButton1");

        buttonGroup10.add(jRadioButton26);
        jRadioButton26.setText("jRadioButton2");

        buttonGroup10.add(jRadioButton27);
        jRadioButton27.setText("jRadioButton3");

        buttonGroup10.add(jRadioButton28);
        jRadioButton28.setText("jRadioButton4");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Best Wishes");

        javax.swing.GroupLayout examQuestionPnaelLayout = new javax.swing.GroupLayout(examQuestionPnael);
        examQuestionPnael.setLayout(examQuestionPnaelLayout);
        examQuestionPnaelLayout.setHorizontalGroup(
            examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                        .addComponent(ques1Rad1)
                        .addGap(42, 42, 42)
                        .addComponent(ques1Rad2)
                        .addGap(69, 69, 69)
                        .addComponent(ques1Rad3)
                        .addGap(76, 76, 76)
                        .addComponent(ques1Rad4)
                        .addGap(133, 133, 133))
                    .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                        .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question1PlaceholderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                                .addComponent(ques2Rad1)
                                .addGap(39, 39, 39)
                                .addComponent(ques2Rad2)
                                .addGap(72, 72, 72)
                                .addComponent(ques2Rad3)
                                .addGap(75, 75, 75)
                                .addComponent(ques2Rad4)
                                .addGap(0, 134, Short.MAX_VALUE))
                            .addComponent(question2PlaceholderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question6PlaceholderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                        .addComponent(jRadioButton12)
                        .addGap(39, 39, 39)
                        .addComponent(jRadioButton11)
                        .addGap(72, 72, 72)
                        .addComponent(jRadioButton10)
                        .addGap(75, 75, 75)
                        .addComponent(jRadioButton9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                        .addComponent(ques1Rad8)
                        .addGap(42, 42, 42)
                        .addComponent(ques1Rad7)
                        .addGap(69, 69, 69)
                        .addComponent(ques1Rad6)
                        .addGap(76, 76, 76)
                        .addComponent(ques1Rad5)
                        .addGap(133, 133, 133))
                    .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                        .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question3PlaceholderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(question4PlaceholderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(question5PlaceholderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                                .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                                        .addComponent(jRadioButton13)
                                        .addGap(39, 39, 39)
                                        .addComponent(jRadioButton14)
                                        .addGap(72, 72, 72)
                                        .addComponent(jRadioButton15)
                                        .addGap(75, 75, 75)
                                        .addComponent(jRadioButton16))
                                    .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                                        .addComponent(ques3Rad1)
                                        .addGap(39, 39, 39)
                                        .addComponent(ques3Rad2)
                                        .addGap(72, 72, 72)
                                        .addComponent(ques3Rad3)
                                        .addGap(75, 75, 75)
                                        .addComponent(ques3Rad4)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question9PlaceholderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                        .addComponent(jRadioButton20)
                        .addGap(39, 39, 39)
                        .addComponent(jRadioButton19)
                        .addGap(72, 72, 72)
                        .addComponent(jRadioButton18)
                        .addGap(75, 75, 75)
                        .addComponent(jRadioButton17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                        .addComponent(ques1Rad12)
                        .addGap(42, 42, 42)
                        .addComponent(ques1Rad11)
                        .addGap(69, 69, 69)
                        .addComponent(ques1Rad10)
                        .addGap(76, 76, 76)
                        .addComponent(ques1Rad9)
                        .addGap(133, 133, 133))
                    .addComponent(question7PlaceholderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                        .addComponent(jRadioButton21)
                        .addGap(39, 39, 39)
                        .addComponent(jRadioButton22)
                        .addGap(72, 72, 72)
                        .addComponent(jRadioButton23)
                        .addGap(75, 75, 75)
                        .addComponent(jRadioButton24)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(question8PlaceholderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question10PlaceholderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                        .addComponent(jRadioButton25)
                        .addGap(39, 39, 39)
                        .addComponent(jRadioButton26)
                        .addGap(72, 72, 72)
                        .addComponent(jRadioButton27)
                        .addGap(75, 75, 75)
                        .addComponent(jRadioButton28)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, examQuestionPnaelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(40, 40, 40))
        );
        examQuestionPnaelLayout.setVerticalGroup(
            examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examQuestionPnaelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(question1PlaceholderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ques1Rad1)
                    .addComponent(ques1Rad2)
                    .addComponent(ques1Rad3)
                    .addComponent(ques1Rad4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question2PlaceholderLabel)
                .addGap(18, 18, 18)
                .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ques2Rad1)
                    .addComponent(ques2Rad2)
                    .addComponent(ques2Rad3)
                    .addComponent(ques2Rad4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question3PlaceholderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ques3Rad1)
                    .addComponent(ques3Rad2)
                    .addComponent(ques3Rad3)
                    .addComponent(ques3Rad4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question4PlaceholderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ques1Rad8)
                    .addComponent(ques1Rad7)
                    .addComponent(ques1Rad6)
                    .addComponent(ques1Rad5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question5PlaceholderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton13)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question6PlaceholderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question7PlaceholderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ques1Rad12)
                    .addComponent(ques1Rad11)
                    .addComponent(ques1Rad10)
                    .addComponent(ques1Rad9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question8PlaceholderLabel)
                .addGap(9, 9, 9)
                .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton21)
                    .addComponent(jRadioButton22)
                    .addComponent(jRadioButton23)
                    .addComponent(jRadioButton24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question9PlaceholderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton20)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton18)
                    .addComponent(jRadioButton17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question10PlaceholderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(examQuestionPnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton25)
                    .addComponent(jRadioButton26)
                    .addComponent(jRadioButton27)
                    .addComponent(jRadioButton28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(examQuestionPnael, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(examInfrormationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(examInfrormationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examQuestionPnael, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamPaper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel durationPlaceholderLabel;
    private javax.swing.JLabel endTimePlaceholderLabel;
    private javax.swing.JLabel examDateLabel;
    private javax.swing.JLabel examDatePlaceholderLabel;
    private javax.swing.JPanel examInfrormationPanel;
    private javax.swing.JPanel examQuestionPnael;
    private final javax.swing.JLabel fcisLabel = new javax.swing.JLabel();
    private javax.swing.JLabel instructorNamePlaceholderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButton ques1Rad1;
    private javax.swing.JRadioButton ques1Rad10;
    private javax.swing.JRadioButton ques1Rad11;
    private javax.swing.JRadioButton ques1Rad12;
    private javax.swing.JRadioButton ques1Rad2;
    private javax.swing.JRadioButton ques1Rad3;
    private javax.swing.JRadioButton ques1Rad4;
    private javax.swing.JRadioButton ques1Rad5;
    private javax.swing.JRadioButton ques1Rad6;
    private javax.swing.JRadioButton ques1Rad7;
    private javax.swing.JRadioButton ques1Rad8;
    private javax.swing.JRadioButton ques1Rad9;
    private javax.swing.JRadioButton ques2Rad1;
    private javax.swing.JRadioButton ques2Rad2;
    private javax.swing.JRadioButton ques2Rad3;
    private javax.swing.JRadioButton ques2Rad4;
    private javax.swing.JRadioButton ques3Rad1;
    private javax.swing.JRadioButton ques3Rad2;
    private javax.swing.JRadioButton ques3Rad3;
    private javax.swing.JRadioButton ques3Rad4;
    private javax.swing.JLabel question10PlaceholderLabel;
    private javax.swing.JLabel question1PlaceholderLabel;
    private javax.swing.JLabel question2PlaceholderLabel;
    private javax.swing.JLabel question3PlaceholderLabel;
    private javax.swing.JLabel question4PlaceholderLabel;
    private javax.swing.JLabel question5PlaceholderLabel;
    private javax.swing.JLabel question6PlaceholderLabel;
    private javax.swing.JLabel question7PlaceholderLabel;
    private javax.swing.JLabel question8PlaceholderLabel;
    private javax.swing.JLabel question9PlaceholderLabel;
    private javax.swing.JLabel subjectNameLabel;
    private javax.swing.JLabel subjectNamePlaceholderLabel;
    // End of variables declaration//GEN-END:variables
}
