/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entities.Course;
import Entities.Class;
import java.awt.event.ActionEvent;
import javax.swing.*;
import java.awt.event.ActionListener;
import Entities.Instructor;
import java.util.Scanner;
import java.util.Vector;

/**
 *
 * @author yn653
 */
public class InstructorDashboard extends javax.swing.JFrame {

    /**
     * Creates new form InstructorDashboard
     */
    Instructor instructor;
        
    /**
     * This constructor initializes the Instructor object in the dashboard and
     * calls all the necessary functions
     *
     * @param instructorUsername
     */
    public InstructorDashboard(String instructorUsername) {
        instructor = new Instructor(instructorUsername);
        initComponents();
        greetInstructor();
        showCourses();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        topBar = new javax.swing.JPanel();
        greetingInstructor = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 1100));

        panel.setBackground(new java.awt.Color(134, 171, 161));
        panel.setPreferredSize(new java.awt.Dimension(798, 850));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel);

        topBar.setBackground(new java.awt.Color(134, 171, 161));

        greetingInstructor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        greetingInstructor.setText("Hello");

        LogoutButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
        topBar.setLayout(topBarLayout);
        topBarLayout.setHorizontalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(greetingInstructor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addGap(105, 105, 105))
        );
        topBarLayout.setVerticalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greetingInstructor)
                    .addComponent(LogoutButton))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(topBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        new Login();
        dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * It modifies the greetingInstructor Text Field to show the name of the
     * instructor
     */
    private void greetInstructor() {
        greetingInstructor.setText(greetingInstructor.getText() + ' ' + instructor.getFirstName());
    }

    /**
     * It displays the names of all the courses in the panel
     */
    private void showCourses() {

        Vector<JLabel> courseName = new Vector<JLabel>();
        Vector< JButton> topicsButtons = new Vector<JButton>(), examsButtons = new Vector<JButton>();
        Vector<Entities.Class> classes = instructor.getClasses();
        for (Entities.Class myClass : classes) {
            courseName.add(new JLabel());
            examsButtons.add(new JButton());
            topicsButtons.add(new JButton());
            //to reterive the names of the courses that the running instructor has
            courseName.lastElement().setText(myClass.getCourse().getName());
        }
        // it defines the spaces between the courses name   
        int delta = 0, currentClassIndex = 0;
        for (JLabel label : courseName) {
            label.setFont(new java.awt.Font("Tahoma", 1, 17));
            label.setBounds(40, 40 + delta, 300, 80);
            examsButtons.elementAt(currentClassIndex).setBounds(380, 65 + delta, 150, 30);
            examsButtons.elementAt(currentClassIndex).setText("Show Exams");
            examsButtons.elementAt(currentClassIndex).setFont(new java.awt.Font("Tahoma", 1, 12));
            topicsButtons.elementAt(currentClassIndex).setBounds(560, 65 + delta, 150, 30);
            topicsButtons.elementAt(currentClassIndex).setText("Show Topics");
            topicsButtons.elementAt(currentClassIndex).setFont(new java.awt.Font("Tahoma", 1, 12));
            topicsButtons.elementAt(currentClassIndex).addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    new Login();
                    dispose();
                }
            });
            Class myClass = classes.elementAt(currentClassIndex);
            examsButtons.elementAt(currentClassIndex).addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    new ViewExamsInstructor(instructor, myClass);
                    dispose();
                }
            });
            panel.add(label);
            panel.add(examsButtons.elementAt(currentClassIndex));
            panel.add(topicsButtons.elementAt(currentClassIndex));
            delta += 50;
            currentClassIndex += 1;
        }

    }

    /**
     * testing the instructor dashboard
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorDashboard("ibrahamhassan").setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel greetingInstructor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel topBar;
    // End of variables declaration//GEN-END:variables
}
