/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.awt.event.ActionEvent;
import javax.swing.*;
import java.awt.event.ActionListener;
import Entities.Instructor;
import java.util.Scanner;


/**
 *
 * @author yn653
 */
public class InstructorDashboard extends javax.swing.JFrame {

    /**
     * Creates new form InstructorDashboard
     */
    
    Instructor instructor; 
    
    /**
     * This constructor initializes the Instructor object in the dashboard and calls all the necessary functions
     * @param instructorUsername
     */
    public InstructorDashboard(String instructorUsername) {
        instructor = new Instructor(instructorUsername);
        initComponents();
        greetInstructor();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        greetingInstructor = new javax.swing.JLabel();
        createExamButton = new javax.swing.JButton();
        examLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        viewExamButton = new javax.swing.JButton();
        viewExamsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 1100));

        jPanel1.setBackground(new java.awt.Color(134, 171, 161));

        greetingInstructor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        greetingInstructor.setText("Hello");

        createExamButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        createExamButton.setText("Create Exam");
        createExamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createExamButtonActionPerformed(evt);
            }
        });

        examLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        examLabel.setText("If you want to create an exam, please click this Button");

        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 14));
        logoutButton.setText("Logout");
        logoutButton.setActionCommand("");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        viewExamButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        viewExamButton.setText("View Exam");
        viewExamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewExamButtonActionPerformed(evt);
            }
        });

        viewExamsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewExamsLabel.setText("If you want to view all the past exams, please click this Button");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(greetingInstructor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(viewExamsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(viewExamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(examLabel)
                        .addGap(18, 18, 18)
                        .addComponent(createExamButton)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(greetingInstructor)
                    .addComponent(logoutButton))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(examLabel)
                    .addComponent(createExamButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewExamButton)
                    .addComponent(viewExamsLabel))
                .addContainerGap(479, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * It modifies the greetingInstructor Text Field to show the name of the instructor
     */
    private void greetInstructor() {
        greetingInstructor.setText(greetingInstructor.getText() + ' ' + instructor.getFirstName());
    }
    
    private void createExamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createExamButtonActionPerformed
        // TODO add your handling code here:
        new CreateQuestion();
        dispose();
        
    }//GEN-LAST:event_createExamButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here: 
    
                new Login();
                dispose();

    }//GEN-LAST:event_logoutButtonActionPerformed

    private void viewExamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewExamButtonActionPerformed
        // TODO add your handling code here:
        new ViewExamsInstructor();
        dispose();
    }//GEN-LAST:event_viewExamButtonActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Scanner input = new Scanner(System.in);
                String username = input.next();
                new InstructorDashboard(username).setVisible(true);
            }
        });
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createExamButton;
    private javax.swing.JLabel examLabel;
    private javax.swing.JLabel greetingInstructor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton viewExamButton;
    private javax.swing.JLabel viewExamsLabel;
    // End of variables declaration//GEN-END:variables
}
