/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import Entities.Instructor; 
import Entities.Class; 
import Entities.Exam;
import java.util.Collection;
import java.util.Collections;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JLabel;
/**
 *
 * @author yn653
 */
public class ViewExamsInstructor extends javax.swing.JFrame {

    /**
     * Creates new form ViewExams
     */
    Instructor instructor;  
    Class instructorClass;
    public ViewExamsInstructor(Instructor instructor , Class instructorClass ) {
        this.instructor = instructor; 
        this.instructorClass = instructorClass;
        initComponents();
        ShowExams();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        currentExamsLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 680));

        jPanel1.setBackground(new java.awt.Color(134, 171, 161));

        currentExamsLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        currentExamsLabel.setText("Exams");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(365, Short.MAX_VALUE)
                .addComponent(currentExamsLabel)
                .addGap(265, 265, 265)
                .addComponent(logoutButton)
                .addGap(26, 26, 26))
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(currentExamsLabel))
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
               logoutButton.addActionListener(new ActionListener() {
             public void actionPerformed(ActionEvent ev){
                new Login();
                dispose();
            }
        });
    }//GEN-LAST:event_logoutButtonActionPerformed
    /**
     * It displays all the exams of the current class ordered according to the following order (Running -> Upcoming -> Previous) 
     */
    private void ShowExams()
    {
        Vector<JLabel> examName = new Vector<JLabel>();
        Vector<JButton> modelsButtons = new Vector<JButton>(), reportButtons = new Vector<JButton>();
        Vector<Exam> exams = instructorClass.getExams();
        Vector<Exam> runningExams = new Vector<Exam>();
        Vector<Exam> upcomingExams = new Vector<Exam>();
        Vector<Exam> finishedExams = new Vector<Exam>();

        for (Entities.Exam exam : exams) {
            
            
            if(exam.isRunning()) {
                runningExams.add(exam);
            } else if(exam.isFinished()) {
                finishedExams.add(exam);
            } else {
                upcomingExams.add(exam);
            }
              
        }
        
        Collections.reverse(finishedExams);
        
        int delta = 0;
        
        for (Exam exam : runningExams) {
            
            examName.add(new JLabel());
            modelsButtons.add(new JButton());
            reportButtons.add(new JButton());
            examName.lastElement().setText(exam.getName());
            examName.lastElement().setBounds(40, 40 + delta, 300, 80);
            examName.lastElement().setFont(new java.awt.Font("Tahoma", 1, 17));
            modelsButtons.lastElement().setText("Show Models");
            modelsButtons.lastElement().setFont(new java.awt.Font("Tahoma", 1, 17));
            modelsButtons.lastElement().setBounds(380, 65 + delta, 150, 30);
            modelsButtons.lastElement().addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    // new Login();
                    dispose();
                }
            });
            reportButtons.lastElement().setText("Show Report");
            reportButtons.lastElement().setFont(new java.awt.Font("Tahoma", 1, 17));
            reportButtons.lastElement().setBounds(560, 65 + delta, 150, 30);
            reportButtons.lastElement().addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    // new Login();
                    dispose();
                }
            });
            panel.add(examName.lastElement());
            panel.add(reportButtons.lastElement());
            panel.add(modelsButtons.lastElement());
            delta += 50;
            
        }
            
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewExamsInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewExamsInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewExamsInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewExamsInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // For testing
                new ViewExamsInstructor(new Instructor("ibrahamhassan"), new Entities.Class(1)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentExamsLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
